import { useEffect, useState } from 'react';
import { Bell, Check, ChevronRight, Globe2, LockKeyhole, Save, Settings, ShieldCheck } from 'lucide-react';
import AppShell from './components/AppShell';
import './operations.css';

const settingTabs = [
  { id: 'general', label: 'General', icon: Settings },
  { id: 'notifications', label: 'Notifications', icon: Bell },
  { id: 'security', label: 'Security', icon: LockKeyhole },
  { id: 'preferences', label: 'Analysis Preferences', icon: SlidersIcon },
  { id: 'system', label: 'System', icon: ShieldCheck },
];

function SlidersIcon(props) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true" {...props}><path d="M4 6h16M4 12h16M4 18h16" /><circle cx="9" cy="6" r="2" fill="currentColor" /><circle cx="15" cy="12" r="2" fill="currentColor" /><circle cx="11" cy="18" r="2" fill="currentColor" /></svg>; }

export default function SettingsPage({ onNavigate }) {
  const [activeTab, setActiveTab] = useState('general');
  const [saved, setSaved] = useState(false);
  const [systemStatus, setSystemStatus] = useState('Checking');
  const [preferences, setPreferences] = useState({ language: 'English', results: '10', timezone: 'IST (UTC+05:30)', scope: 'BIS + related references', score: '80%', amended: true, superseded: false, certification: true });
  useEffect(() => { fetch('http://localhost:8000/health').then((response) => { if (!response.ok) throw new Error('unavailable'); setSystemStatus('Connected'); }).catch(() => setSystemStatus('Unavailable')); }, []);
  function update(key, value) { setPreferences((current) => ({ ...current, [key]: value })); setSaved(false); }
  function save() { setSaved(true); }
  return <AppShell activePage="settings" currentPage="Settings" onNavigate={onNavigate}>
    <main className="operations-workspace settings-workspace" aria-labelledby="settings-title"><header className="operations-header"><div><span className="operations-kicker">APPLICATION CONTROL</span><h1 id="settings-title">Settings</h1><p>Manage application preferences, notifications, security, and procurement intelligence configuration.</p></div></header><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{settingTabs.map(({ id, label, icon: Icon }) => <button className={activeTab === id ? 'is-active' : ''} type="button" key={id} onClick={() => setActiveTab(id)}><Icon size={17} />{label}<ChevronRight size={14} /></button>)}</nav><section className="settings-panel"><div className="settings-panel-heading"><div><span className="operations-kicker">{settingTabs.find((tab) => tab.id === activeTab)?.label}</span><h2>{activeTab === 'general' ? 'General preferences' : activeTab === 'notifications' ? 'Notification preferences' : activeTab === 'security' ? 'Security overview' : activeTab === 'preferences' ? 'Analysis preferences' : 'System status'}</h2></div>{activeTab === 'general' || activeTab === 'preferences' ? <button className="settings-save-button" type="button" onClick={save}><Save size={15} /> Save Changes</button> : null}</div>
{activeTab === 'general' ? <div className="settings-form"><label>Organization / Department<input value="National Office" readOnly /></label><label>Default Analysis Language<select value={preferences.language} onChange={(event) => update('language', event.target.value)}><option>English</option><option>Hindi</option></select></label><label>Default Results Per Page<select value={preferences.results} onChange={(event) => update('results', event.target.value)}><option>10</option><option>25</option><option>50</option></select></label><label>Timezone<select value={preferences.timezone} onChange={(event) => update('timezone', event.target.value)}><option>IST (UTC+05:30)</option><option>UTC</option></select></label><button className="settings-reset-button" type="button" onClick={() => setPreferences((current) => ({ ...current, language: 'English', results: '10', timezone: 'IST (UTC+05:30)' }))}>Reset</button></div> : null}
{activeTab === 'notifications' ? <div className="notification-settings">{['Tender analysis completed', 'Compliance issues detected', 'Standards amended', 'Report generation completed'].map((label) => <div className="notification-setting" key={label}><div><strong>{label}</strong><span>Receive important workflow updates.</span></div><label><input type="checkbox" defaultChecked /><span>Email</span></label><label><input type="checkbox" defaultChecked /><span>In-app</span></label></div>)}</div> : null}
{activeTab === 'security' ? <div className="security-grid">{[['Account Security', 'Managed by National Office policy'], ['Session Management', 'Standard session controls active'], ['Last Sign-in', 'No sign-in history is available in this frontend'], ['Two-factor Authentication', 'Not configured by the current backend']].map(([title, detail]) => <article key={title}><LockKeyhole size={18} /><div><strong>{title}</strong><p>{detail}</p></div><span className="settings-status muted">Informational</span></article>)}</div> : null}
{activeTab === 'preferences' ? <div className="settings-form"><label>Preferred Standards Scope<select value={preferences.scope} onChange={(event) => update('scope', event.target.value)}><option>BIS only</option><option>BIS + related references</option></select></label><label>Minimum Match Score<select value={preferences.score} onChange={(event) => update('score', event.target.value)}><option>80%</option><option>70%</option><option>90%</option></select></label><div className="settings-toggle-row"><span>Include amended standards</span><button className={preferences.amended ? 'toggle is-on' : 'toggle'} type="button" onClick={() => update('amended', !preferences.amended)} aria-pressed={preferences.amended}><span /></button></div><div className="settings-toggle-row"><span>Include superseded standards</span><button className={preferences.superseded ? 'toggle is-on' : 'toggle'} type="button" onClick={() => update('superseded', !preferences.superseded)} aria-pressed={preferences.superseded}><span /></button></div><div className="settings-toggle-row"><span>Show certification guidance</span><button className={preferences.certification ? 'toggle is-on' : 'toggle'} type="button" onClick={() => update('certification', !preferences.certification)} aria-pressed={preferences.certification}><span /></button></div></div> : null}
{activeTab === 'system' ? <div className="system-status-list">{[['System Status', systemStatus], ['BIS Standards Service', systemStatus === 'Connected' ? 'Operational' : systemStatus], ['Analysis Service', systemStatus === 'Connected' ? 'Operational' : 'Unavailable'], ['Database', systemStatus === 'Connected' ? 'Operational' : 'Unavailable']].map(([label, value]) => <div key={label}><div><Globe2 size={17} /><strong>{label}</strong></div><span className={value === 'Operational' || value === 'Connected' ? 'settings-status is-ok' : 'settings-status muted'}><Check size={13} /> {value}</span></div>)}</div> : null}
{saved ? <p className="settings-saved" role="status"><Check size={15} /> Preferences saved for this session.</p> : null}</section></div></main>
  </AppShell>;
}
